_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 80
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 80
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
batch_size_test:
    value: 1
batch_size_training:
    value: 8
batch_size_validation:
    value: 4
encoder:
    value: efficientnet-b4
epochs:
    value: 1
learning_rate:
    value: 0.0005
model:
    value: DeepLabV3+
num_workers:
    value: 16
optimizer:
    value: Adam
patch_size:
    value: 512
